[tools]
bat              = "latest"
bun              = "latest"
claude-code      = "latest"
cocoapods        = "1"
colima           = "latest"
devcontainer-cli = "latest"
eza              = "latest"
fastfetch        = "latest"
fd               = "latest"
ffmpeg           = "latest"
fzf              = "latest"
gcloud           = "latest"
gemini-cli       = "latest"
gh               = "latest"
go               = "latest"
java             = "21"
jq               = "latest"
lazydocker       = "latest"
lazygit          = "latest"
lima             = "2"
neovim           = "latest"
node             = "lts"
ollama           = "latest"
opencode         = "latest"
pnpm             = "10"
python           = "3.11"
resvg            = "latest"
ripgrep          = "latest"
rust             = "1"
rust-analyzer    = "latest"
sqlite           = "3"
starship         = "latest"
terraform        = "latest"
tflint           = "latest"
tmux             = "latest"
uv               = "latest"
wrangler         = "4"
yarn             = "1"
yazi             = "latest"
yq               = "latest"

[settings]
go_set_gobin                        = true
pipx_uvx                            = true
experimental                        = true
idiomatic_version_file_enable_tools = ["python"]
disable_tools                       = ["ruby"]
